version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mobile-kiosk/source
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
